app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('members/', include('members.urls')),
    path('', views.index, name='index'),

    # path('media/<str:path>/', 특정view_function),

] + static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),

    path('facebook-login/', views.facebook_login, name='facebook-login')
]

app/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('<int:pk>/', views.post_detail, name='post-detail'),
    path('<int:pk>/delete/', views.post_delete, name='post-delete'),
    path('create/', views.post_create, name='post-create'),

    path('<int:pk>/comment/create/', views.comment_create, name='comment-create'),
]

app/templates/base.html
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Instagram</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<h1><a href="{% url 'index' %}">Instagram</a></h1>
		<div>
			<!--
				user가 인증되어있으면 '로그아웃하기'라는 링크를 보여주고
				아니면 '로그인하기'링크 보여주기

				logout_view를 구현
					request.method가 POST일 경우,
					request.user를 로그아웃시킴

				URL: /members/logout/
				view: members.views.logout_view
				로그아웃 완료 후에는 index로 redirect

				form action: logout_view

			-->
			{% if user.is_authenticated %}
				<span>{{ user }}로 로그인 중</span>
				<form action="{% url 'members:logout' %}" method="POST">
					{% csrf_token %}
					<button class="btn btn-primary btn-sm" type="submit">로그아웃하기</button>
				</form>
			{% else %}
				<a class="btn btn-primary btn-sm" href="{% url 'members:login' %}">로그인하기</a>
				<a class="btn btn-primary btn-sm" href="{% url 'members:signup' %}">회원가입하기</a>
			{% endif %}
			<a class="btn btn-primary btn-sm" href="{% url 'posts:post-create' %}">글 쓰기</a>
		</div>
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>